trigger:
- DEV

pool:
  vmImage: ubuntu-latest

variables:
- group: IICS_SECRETS

stages:

# -----------------------
# STAGE DEV
# -----------------------
- stage: DEV
  displayName: "Build / Export from DEV"
  jobs:
  - job: Build
    steps:
    - checkout: self

    - script: |
        echo "Exportando assets desde DEV"
        echo "Username: $USERNAME"
      env:
        USERNAME: $(DEV_IICS_USERNAME)
        PASSWORD: $(DEV_IICS_PASSWORD)

# -----------------------
# STAGE QA
# -----------------------
- stage: QA
  displayName: "Deploy to QA"
  dependsOn: DEV
  jobs:
  - deployment: DeployQA
    environment: QA
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Promocionando a QA"
              echo "Username: $USERNAME"
            env:
              USERNAME: $(QA_IICS_USERNAME)
              PASSWORD: $(QA_IICS_PASSWORD)