trigger:
- DEV

pool:
  vmImage: ubuntu-latest

variables:
- group: IICS_SECRETS

stages:

# -----------------------
# STAGE DEV
# -----------------------
- stage: DEV
  displayName: "Build / Export from DEV"

  jobs:
  - job: Build
    displayName: "Export assets from DEV"

    steps:
    - checkout: self
      clean: true

    - script: |
        echo "Exportando assets desde DEV"
        echo "Commit que dispara el pipeline: $(Build.SourceVersion)"
        echo "Username: $(DEV_IICS_USERNAME)"

        mkdir export
        echo "Simulación export IICS assets" > export/assets.txt
      displayName: "Export IICS assets"

    - task: PublishPipelineArtifact@1
      displayName: "Publicar artefacto DEV"
      inputs:
        targetPath: export
        artifact: DEV_ASSETS
        publishLocation: pipeline


# -----------------------
# STAGE QA
# -----------------------
- stage: QA
  displayName: "Deploy to QA"
  dependsOn: DEV
  condition: succeeded()

  jobs:
  - deployment: DeployQA
    displayName: "Deploy assets to QA"
    environment: QA

    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: none

          - task: DownloadPipelineArtifact@2
            displayName: "Descargar artefacto generado en DEV"
            inputs:
              artifact: DEV_ASSETS
              path: $(Pipeline.Workspace)/DEV_ASSETS

          - script: |
              echo "Promocionando a QA"
              echo "Commit promovido: $(Build.SourceVersion)"
              echo "Username QA: $(QA_IICS_USERNAME)"
              ls -R $(Pipeline.Workspace)/DEV_ASSETS
            displayName: "Deploy to QA"