name: IICS Deployment

on:
  push:
    branches:
      - DEV

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use secrets
        env:
          USERNAME: ${{ secrets.UAT_IICS_USERNAME }}
          PASSWORD: ${{ secrets.UAT_IICS_PASSWORD }}
        run: |
          echo "Usuario configurado"