runtime_mapping:
  - DEV:
      name: SDCAMDMSA01
      id: 011EE92500000000001I
      federatedId: 9xO6JQYRdY1gX3ACS2wkei
    TARGET:
      name: AG_IICS_QA_CDI
      id: 011EE92500000000002V
      federatedId: ejoS1HHsMOhig0oh80MwIH
